name: Build XeLaTeX document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile XeLaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: bit-true-arithmetics.tex
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: bit-true-arithmetics.pdf
          compression-level: 9
